export const ANYBODY_FETCH_SEARCH_RESULT = 'ANYBODY_FETCH_SEARCH_RESULT';
export const ANYBODY_FETCH_SEARCH_RESULT_SUCCESS = 'ANYBODY_FETCH_SEARCH_RESULT_SUCCESS';
export const ANYBODY_FETCH_SEARCH_RESULT_FAILURE = 'ANYBODY_FETCH_SEARCH_RESULT_FAILURE';
export const RESET_ANYBODY_FETCH_SEARCH_RESULT = 'RESET_ANYBODY_FETCH_SEARCH_RESULT';