export const ANYBODY_FETCH_HOME_REQUESTS = 'ANYBODY_FETCH_HOME_REQUESTS';
export const ANYBODY_FETCH_HOME_REQUESTS_SUCCESS = 'ANYBODY_FETCH_HOME_REQUESTS_SUCCESS';
export const ANYBODY_FETCH_HOME_REQUESTS_FAILURE = 'ANYBODY_FETCH_HOME_REQUESTS_FAILURE';

export const ANYBODY_FETCH_REQUESTS_BY_QUERY = 'ANYBODY_FETCH_REQUESTS_BY_QUERY';
export const ANYBODY_FETCH_REQUESTS_BY_QUERY_SUCCESS = 'ANYBODY_FETCH_REQUESTS_BY_QUERY_SUCCESS';
export const ANYBODY_FETCH_REQUESTS_BY_QUERY_FAILURE = 'ANYBODY_FETCH_REQUESTS_BY_QUERY_FAILURE';

export const ANYBODY_FETCH_SEARCH_ALL_OPTIONS = 'ANYBODY_FETCH_SEARCH_ALL_OPTIONS';
export const ANYBODY_FETCH_SEARCH_ALL_OPTIONS_SUCCESS = 'ANYBODY_FETCH_SEARCH_ALL_OPTIONS_SUCCESS';
export const ANYBODY_FETCH_SEARCH_ALL_OPTIONS_FAILURE = 'ANYBODY_FETCH_SEARCH_ALL_OPTIONS_FAILURE';

export const ANYBODY_FETCH_MAIN_REQUEST = 'ANYBODY_FETCH_MAIN_REQUEST';
export const ANYBODY_FETCH_REDIRECT_MAIN_REQUEST = 'ANYBODY_FETCH_REDIRECT_MAIN_REQUEST';
export const ANYBODY_FETCH_MAIN_REQUEST_SUCCESS = 'ANYBODY_FETCH_MAIN_REQUEST_SUCCESS';
export const ANYBODY_FETCH_MAIN_REQUEST_FAILURE = 'ANYBODY_FETCH_MAIN_REQUEST_FAILURE';
export const RESET_ANYBODY_FETCH_MAIN_REQUEST = 'RESET_ANYBODY_FETCH_MAIN_REQUEST';