export const USER_FETCH_MY_SIGN_INFO = 'USER_FETCH_MY_SIGN_INFO';
export const USER_FETCH_MY_SIGN_INFO_SUCCESS = 'USER_FETCH_MY_SIGN_INFO_SUCCESS';
export const USER_FETCH_MY_SIGN_INFO_FAILURE = 'USER_FETCH_MY_SIGN_INFO_FAILURE';
export const RESET_USER_FETCH_MY_SIGN_INFO = 'RESET_USER_FETCH_MY_SIGN_INFO';

export const USER_FETCH_AGE_LIST = 'USER_FETCH_AGE_LIST';
export const USER_FETCH_AGE_LIST_SUCCESS = 'USER_FETCH_AGE_LIST_SUCCESS';
export const USER_FETCH_AGE_LIST_FAILURE = 'USER_FETCH_AGE_LIST_FAILURE';

export const USER_FETCH_CITY_LIST = 'USER_FETCH_CITY_LIST';
export const USER_FETCH_CITY_LIST_SUCCESS = 'USER_FETCH_CITY_LIST_SUCCESS';
export const USER_FETCH_CITY_LIST_FAILURE = 'USER_FETCH_CITY_LIST_FAILURE';

export const USER_UPDATE_MY_SIGN_INFO = 'USER_UPDATE_MY_SIGN_INFO';
export const USER_UPDATE_MY_SIGN_INFO_SUCCESS = 'USER_UPDATE_MY_SIGN_INFO_SUCCESS';
export const USER_UPDATE_MY_SIGN_INFO_FAILURE = 'USER_UPDATE_MY_SIGN_INFO_FAILURE';
export const RESET_USER_UPDATE_MY_SIGN_INFO = 'RESET_USER_UPDATE_MY_SIGN_INFO';