export const GUEST_EXECUTE_LOGIN_BY_MODEL = 'GUEST_EXECUTE_LOGIN_BY_MODEL';
export const GUEST_EXECUTE_LOGIN_BY_MODEL_SUCCESS = 'GUEST_EXECUTE_LOGIN_BY_MODEL_SUCCESS';
export const GUEST_EXECUTE_LOGIN_BY_MODEL_FAILURE = 'GUEST_EXECUTE_LOGIN_BY_MODEL_FAILURE';
export const RESET_GUEST_EXECUTE_LOGIN_BY_MODEL = 'RESET_GUEST_EXECUTE_LOGIN_BY_MODEL';

export const GUEST_FETCH_AGE_LIST = 'GUEST_FETCH_AGE_LIST';
export const GUEST_FETCH_AGE_LIST_SUCCESS = 'GUEST_FETCH_AGE_LIST_SUCCESS';
export const GUEST_FETCH_AGE_LIST_FAILURE = 'GUEST_FETCH_AGE_LIST_FAILURE';

export const GUEST_FETCH_CITY_LIST = 'GUEST_FETCH_CITY_LIST';
export const GUEST_FETCH_CITY_LIST_SUCCESS = 'GUEST_FETCH_CITY_LIST_SUCCESS';
export const GUEST_FETCH_CITY_LIST_FAILURE = 'GUEST_FETCH_CITY_LIST_FAILURE';

export const GUEST_EXECUTE_SIGN_UP_BY_MODEL = 'GUEST_EXECUTE_SIGN_UP_BY_MODEL';
export const GUEST_EXECUTE_SIGN_UP_BY_MODEL_SUCCESS = 'GUEST_EXECUTE_SIGN_UP_BY_MODEL_SUCCESS';
export const GUEST_EXECUTE_SIGN_UP_BY_MODEL_FAILURE = 'GUEST_EXECUTE_SIGN_UP_BY_MODEL_FAILURE';
export const RESET_GUEST_EXECUTE_SIGN_UP_BY_MODEL = 'RESET_GUEST_EXECUTE_SIGN_UP_BY_MODEL';