export const ADMIN_FETCH_ALL_TITLES = 'ADMIN_FETCH_ALL_TITLES';
export const ADMIN_FETCH_ALL_TITLES_SUCCESS = 'ADMIN_FETCH_ALL_TITLES_SUCCESS';
export const ADMIN_FETCH_ALL_TITLES_FAILURE = 'ADMIN_FETCH_ALL_TITLES_FAILURE';
export const RESET_ADMIN_FETCH_ALL_TITLES = 'RESET_ADMIN_FETCH_ALL_TITLES';

export const ANYBODY_FETCH_MAIN_TITLE_LIST = 'ANYBODY_FETCH_MAIN_TITLE_LIST';
export const ANYBODY_FETCH_MAIN_TITLE_LIST_SUCCESS = 'ANYBODY_FETCH_MAIN_TITLE_LIST_SUCCESS';
export const ANYBODY_FETCH_MAIN_TITLE_LIST_FAILURE = 'ANYBODY_FETCH_MAIN_TITLE_LIST_FAILURE';
export const RESET_ANYBODY_FETCH_MAIN_TITLE_LIST = 'RESET_ANYBODY_FETCH_MAIN_TITLE_LIST';

export const ANYBODY_FETCH_HAS_MY_TITLE = 'ANYBODY_FETCH_HAS_MY_TITLE';
export const ANYBODY_FETCH_HAS_MY_TITLE_SUCCESS = 'ANYBODY_FETCH_HAS_MY_TITLE_SUCCESS';
export const ANYBODY_FETCH_HAS_MY_TITLE_FAILURE = 'ANYBODY_FETCH_HAS_MY_TITLE_FAILURE';
export const RESET_ANYBODY_FETCH_HAS_MY_TITLE = 'RESET_ANYBODY_FETCH_HAS_MY_TITLE';

export const ANYBODY_SAVE_MY_TITLE = 'ANYBODY_SAVE_MY_TITLE';
export const ANYBODY_SAVE_MY_TITLE_SUCCESS = 'ANYBODY_SAVE_MY_TITLE_SUCCESS';
export const ANYBODY_SAVE_MY_TITLE_FAILURE = 'ANYBODY_SAVE_MY_TITLE_FAILURE';

export const ANYBODY_DELETE_TITLE_BY_ID = 'ANYBODY_DELETE_TITLE_BY_ID';
export const ANYBODY_DELETE_TITLE_BY_ID_SUCCESS = 'ANYBODY_DELETE_TITLE_BY_ID_SUCCESS';
export const ANYBODY_DELETE_TITLE_BY_ID_FAILURE = 'ANYBODY_DELETE_TITLE_BY_ID_FAILURE';

export const ADMIN_DELETE_TITLES_PARTITION = 'ADMIN_DELETE_TITLES_PARTITION';
export const ADMIN_DELETE_TITLES_PARTITION_SUCCESS = 'ADMIN_DELETE_TITLES_PARTITION_SUCCESS';
export const ADMIN_DELETE_TITLES_PARTITION_FAILURE = 'ADMIN_DELETE_TITLES_PARTITION_FAILURE';

export const RESET_ANYBODY_SAVE_MY_TITLE = 'RESET_ANYBODY_SAVE_MY_TITLE';
