export const ANYBODY_FETCH_HOME_REQUESTS = 'ANYBODY_FETCH_HOME_REQUESTS';
export const ANYBODY_FETCH_HOME_REQUESTS_SUCCESS = 'ANYBODY_FETCH_HOME_REQUESTS_SUCCESS';
export const ANYBODY_FETCH_HOME_REQUESTS_FAILURE = 'ANYBODY_FETCH_HOME_REQUESTS_FAILURE';

export const ANYBODY_FETCH_REQUESTS_BY_QUERY = 'ANYBODY_FETCH_REQUESTS_BY_QUERY';
export const ANYBODY_FETCH_REQUESTS_BY_QUERY_SUCCESS = 'ANYBODY_FETCH_REQUESTS_BY_QUERY_SUCCESS';
export const ANYBODY_FETCH_REQUESTS_BY_QUERY_FAILURE = 'ANYBODY_FETCH_REQUESTS_BY_QUERY_FAILURE';

