export const ANYBODY_FETCH_COMMENT_LIST = 'ANYBODY_FETCH_COMMENT_LIST';
export const ANYBODY_FETCH_COMMENT_LIST_SUCCESS = 'ANYBODY_FETCH_COMMENT_LIST_SUCCESS';
export const ANYBODY_FETCH_COMMENT_LIST_FAILURE = 'ANYBODY_FETCH_COMMENT_LIST_FAILURE';
export const RESET_ANYBODY_FETCH_COMMENT_LIST = 'RESET_ANYBODY_FETCH_COMMENT_LIST';

export const ANYBODY_SAVE_COMMENT_BY_MODEL = 'ANYBODY_SAVE_COMMENT_BY_MODEL';
export const ANYBODY_SAVE_COMMENT_BY_MODEL_SUCCESS = 'ANYBODY_SAVE_COMMENT_BY_MODEL_SUCCESS';
export const ANYBODY_SAVE_COMMENT_BY_MODEL_FAILURE = 'ANYBODY_SAVE_COMMENT_BY_MODEL_FAILURE';

export const ANYBODY_DELETE_COMMENT_BY_ID = 'ANYBODY_DELETE_COMMENT_BY_ID';
export const ANYBODY_DELETE_COMMENT_BY_ID_SUCCESS = 'ANYBODY_DELETE_COMMENT_BY_ID_SUCCESS';
export const ANYBODY_DELETE_COMMENT_BY_ID_FAILURE = 'ANYBODY_DELETE_COMMENT_BY_ID_FAILURE';

export const RESET_ANYBODY_SAVE_COMMENT_BY_MODEL = 'RESET_ANYBODY_SAVE_COMMENT_BY_MODEL';