export const ANYBODY_FETCH_CATEGORY_LIST = 'ANYBODY_FETCH_CATEGORY_LIST';
export const ANYBODY_FETCH_CATEGORY_LIST_SUCCESS = 'ANYBODY_FETCH_CATEGORY_LIST_SUCCESS';
export const ANYBODY_FETCH_CATEGORY_LIST_FAILURE = 'ANYBODY_FETCH_CATEGORY_LIST_FAILURE';

export const ANYBODY_FETCH_CATEGORY_ELEMENT = 'ANYBODY_FETCH_CATEGORY_ELEMENT';
export const ANYBODY_FETCH_CATEGORY_ELEMENT_SUCCESS = 'ANYBODY_FETCH_CATEGORY_ELEMENT_SUCCESS';
export const ANYBODY_FETCH_CATEGORY_ELEMENT_FAILURE = 'ANYBODY_FETCH_CATEGORY_ELEMENT_FAILURE';
export const RESET_ANYBODY_FETCH_CATEGORY_ELEMENT = 'RESET_ANYBODY_FETCH_CATEGORY_ELEMENT';